version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: multilimp-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: multilimp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - multilimp-network

volumes:
  postgres_data:


networks:
  multilimp-network:
    driver: bridge
